### ISSUE TITLE
Sync-gateway not excepting any test function provided in synctos tests.

### ISSUE THREAD

**Issue by shashanktomar** [Kashoo/synctos#116]
**Process**
- Copy any test sync function from synctos repo. And create a simple walrus config.
- Bring up sync-gateway server
- load admin > sync page
- chrome dev tools report the serve error while sync-function compilation

`Uncaught SyntaxError: Invalid or unexpected token
    at compileSyncFunction (sync:580)
    at SyncModel.setSyncFunction (sync:580)
    at sync:580
    at Object.callback (sync:579)
    at on_end (sync:579)
    at XMLHttpRequest.on_state_change (sync:579)`

- I tried to see what it is compiling to and this is the stuff inside validation functions.

`function isIso8601DateTimeString(value) {
      var regex = new RegExp('^(([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]))([T ]([01][0-9]|2[0-4])(:[0-5][0-9])?(:[0-5][0-9])?([\\.,][0-9]{1,3})?)?([zZ]|([\\+-])([01][0-9]|2[0-3]):?([0-5][0-9])?)?;function makeArray(maybeArray){return Array.isArray(maybeArray)?maybeArray:[maybeArray]}function inArray(string,array){return-1!=array.indexOf(string)}function anyInArray(any,array){for(var i=0;i<any.length;++i)if(inArray(any[i],array))return!0;return!1}function requireUser(names){if(shouldValidate&&(names=makeArray(names),!inArray(realUserCtx.name,names)))throw{forbidden:"wrong user"}}function requireRole(roles){if(shouldValidate&&(roles=makeArray(roles),!anyInArray(realUserCtx.roles,roles)))throw{forbidden:"missing role"}}function requireAccess(channels){if(shouldValidate&&(channels=makeArray(channels),!anyInArray(realUserCtx.channels,channels)))throw{forbidden:"missing channel access"}}function channel(){var args=Array.prototype.slice.apply(arguments);results.channels=Array.prototype.concat.apply(results.channels,args)}function access(users,channels){results.access.push({users:makeArray(users),channels:makeArray(channels)})}function role(users,channels){results.roles.push({users:makeArray(users),channels:makeArray(channels)})}function reject(code,message){results.reject=[code,message]}var _=require("underscore"),log=console.log.bind(console),shouldValidate=null!==realUserCtx&&null!==realUserCtx.name,results={channels:[],access:[],roles:[],reject:!1};try{syncFun(newDoc,oldDoc)}catch(x){if(x.forbidden)reject(403,x.forbidden);else{if(!x.unauthorized)throw x;reject(401,x.unauthorized)}}return results});
      return regex.test(value);
    }`

- You can see some junk stuff appended to the validation regex.

Am I missing something here?

**Comment by OldSneerJaw** [comment]
@shashanktomar, when you say "Copy any test sync function from synctos repo", are you referring to the `test-*-sync-function.js` files that are created in the synctos repo's `build/sync-functions` directory when you run `npm test`? If so, have you copied the _full_ file contents and then surrounded it with backticks (\`) when pasting it into the Sync Gateway configuration file? See the official document on [configuration files](https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/config-properties/index.html) for more info.

**Comment by shashanktomar** [comment]
@OldSneerJaw yes you are right. Here is my exact config file.

[gist](https://gist.github.com/shashanktomar/b497c5a7c65f1415eb743f637612fa2b)

**Comment by OldSneerJaw** [comment]
@shashanktomar, I see what you mean now. I'll look into it further.

**Comment by OldSneerJaw** [comment]
I have discovered the root of the problem. When the [Sync Gateway admin UI](https://github.com/couchbaselabs/sync_gateway_admin_ui) injects a sync function into its editor view (see [compileSyncFunction](https://github.com/couchbaselabs/sync_gateway_admin_ui/blob/139c58897072434066f5d0a56589170786371d3c/src/js/syncModel.js#L458-L465) in syncModel.js), it uses the version of the JavaScript `String.replace` function that expects the replacement as a string. As noted by the Mozilla Developer Network documentation, this [version](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter) of the function includes support for special replacement patterns. One of which is `$'` ("Inserts the portion of the string that follows the matched substring"), which appears at the end of a number of regular expressions in sync functions generated by synctos.

The ideal solution would be to update the source project to use a replacement function rather than a replacement string. However, it appears the project in question is in the middle of a major overhaul that has stalled out; the last commit to the [dev](https://github.com/couchbaselabs/sync_gateway_admin_ui/tree/dev) branch is from June 2016. In the meantime I will switch synctos to use double quotes for those regular expressions that end with a `$` as a workaround to this issue.

**Comment by OldSneerJaw** [comment]
I created https://github.com/couchbaselabs/sync_gateway_admin_ui/issues/47 to address the bug at the source in the Sync Gateway admin UI project.

**Comment by shashanktomar** [comment]
Thanks for the fix @OldSneerJaw

**Comment by dkichler** [comment]
Satisfied by #117

**Comment by OldSneerJaw** [comment]
@shashanktomar, version 1.9.1 has been published with the workaround to this issue.
