### ISSUE TITLE
Using the test helper functionality by passing in the couchbase config JSON or function directly

### ISSUE THREAD

**Issue by dlbuckley** [Kashoo/synctos#121]
## Overview
I have a need to use the **test-helper.js** functionality but without using the sync function generation. 

With that in mind I simply want to pass in the couchbase configuration .json file path, or pass in the sync function directly to the test helper so it can be tested without the need for having the sync function in a separate file or a configuration.

## Details
Currently the only methods for initialising the testHelper take a file path to a definition file or to a .js file that contains the sync function. If the test helper is initialised with no arguments it defaults to the method that initialises with the sync function file path which then crashes as no path is supplied.

Ideally the default init function would be able to be used with no arguments so the 'syncFunction' property can be set from an external source, that way it's up to the user how they load the sync function into the test helper.

If this isn't desired then the ability to load in the actual couch base configuration .json would be just as good.

**Comment by OldSneerJaw** [comment]
Interesting. Would you care to elaborate further on your use case?

The `test-helper` module isn't built to support sync functions that weren't generated by synctos, so while we can theoretically add an initialization function that accepts a sync function's contents as a string, there's no guarantee that it will work well with your own custom sync function.

Since synctos itself has very high test coverage, I strongly recommend that you implement your document schema as synctos document definitions and then use `test-helper` to write test cases for the specific parts that include custom validation logic (e.g. custom type filters, custom field validation, etc). Then you can load the document definitions file(s) or the generated sync function(s) from your test cases normally.

**Comment by OldSneerJaw** [comment]
Closing this issue. Support for sync functions that were not generated by synctos will not be available in the foreseeable future.
