### ISSUE TITLE
Unable to delete document through on sync gateway

### ISSUE THREAD

**Issue by utekau** [Kashoo/synctos#300]
Hi,

We found a potential bug when we tried to delete an existing document from couchbase. After sending the delete request, we get an error message like that : "_Invalid Observation document: item \"templateRevisionInfo.schema\" must not be null or missing; property \"templateRevisionInfo.$schema\" is not supported_". Interestingly, the current document (whose revision is 13-485758e443ba6619454714dd97da51e6) doesn't include any field such that _$schema_, its totally fine in terms of model that we define in configuration. In the past, we successfully update the document field and incremented its revision. I don't understand why it is catched by the rules and the not all allow to delete.

In the below you can see the logs from sync gateway.
Document id: Observation::burakUWP

`12:22:30.618019 2018-04-10T12:22:30.618Z HTTP:  #165: DELETE /test-dw-uwp/Observation::burakUWP?rev=13-485758e443ba6619454714dd97da51e6 (as ADMIN)

12:22:30.619367 2018-04-10T12:22:30.619Z CRUD+: Invoking sync on doc "Observation::burakUWP" rev 14-25a4aaf359dca656f0416979f50925ff

12:22:30.622448 2018-04-10T12:22:30.622Z CRUD+: Saving old revision "Observation::burakUWP" / "13-485758e443ba6619454714dd97da51e6" (2373 bytes)

12:22:30.625538 2018-04-10T12:22:30.625Z CRUD+: Backed up obsolete rev "Observation::burakUWP"/"13-485758e443ba6619454714dd97da51e6"

12:22:30.626791 2018-04-10T12:22:30.626Z CRUD+: updateDoc("Observation::burakUWP"): Rev "14-25a4aaf359dca656f0416979f50925ff" causes "11-80a1e32f34ba86485260926d0d7d558c6c71acf7" to become current again

12:22:30.626814 2018-04-10T12:22:30.626Z CRUD+: Invoking sync on doc "Observation::burakUWP" rev 11-80a1e32f34ba86485260926d0d7d558c6c71acf7

12:22:30.627798 2018-04-10T12:22:30.627Z CRUD+: No old revision "Observation::burakUWP" / "10-b96751505f60bea8d9d3d1b2c004a0d82b9dd1e5"

12:22:30.629170 2018-04-10T12:22:30.629Z CRUD+: No old revision "Observation::burakUWP" / "9-7a40c2651fa86489ea59de2e6d489864b3d49642"

12:22:30.629491 2018-04-10T12:22:30.629Z CRUD+: No old revision "Observation::burakUWP" / "8-2cfd23c5f4d481036028c3a1e0a7dbf13edf6358"

12:22:30.630251 2018-04-10T12:22:30.630Z CRUD+: No old revision "Observation::burakUWP" / "7-e5b606fd8bed824fe4eae3e0e72b7a2b92c9732b"

12:22:30.630415 2018-04-10T12:22:30.630Z CRUD+: No old revision "Observation::burakUWP" / "6-604e729f28976a2b7b2c5ca79bb6cc1b22c9c9e9"

12:22:30.635224 2018-04-10T12:22:30.635Z CRUD+: No old revision "Observation::burakUWP" / "5-eb68b13c6931b91eee54718a3525b3dfeaa451d5"

12:22:30.635373 2018-04-10T12:22:30.635Z CRUD+: No old revision "Observation::burakUWP" / "4-015ee135f2c3bdf2a106fec68a065f7cc35c48ba"

12:22:30.635509 2018-04-10T12:22:30.635Z CRUD+: No old revision "Observation::burakUWP" / "3-7bf93393bf9533ba52676c58f8d19d93b09eaeb8"

12:22:30.635878 2018-04-10T12:22:30.635Z CRUD+: No old revision "Observation::burakUWP" / "2-c175bd6b2f6427a2980338b55f29a3e5480090d1"

12:22:30.636013 2018-04-10T12:22:30.636Z CRUD+: No old revision "Observation::burakUWP" / "1-b2d1c7e25553551cd4074a0512a4724d"

12:22:30.663009 2018-04-10T12:22:30.662Z Sync fn rejected: new=map[category:My Observations description:Burak Observation Test UWP title:Observation Test 1 _rev:11-80a1e32f34ba86485260926d0d7d558c6c71acf7 form:map[sections:[map[rows:[map[columns:[map[formItems:[map[required:false type:Image cssClass: image:assets/img/Valve.png imagePosition:bottom imageType:fixed question:Acme image:]] colspan:col-xs-4] map[colspan:col-xs-4 formItems:[map[type:Text question:Project: rows:3 cssClass:ciw-text ciw-height-192 orientation:vertical placeholder:... readonly:true required:false answer:Acme Combined-Cycle Power Plant columnWidths:<nil>]]] map[colspan:col-xs-4 formItems:[map[answer:P-ACME-CCP-09345 cssClass:ciw-text ciw-height-192 readonly:true columnWidths:<nil> orientation:vertical placeholder:... question:Number: required:false rows:2 type:Text]]]]] map[columns:[map[formItems:[map[placeholder:Enter ID... question:Database ID: type:Text answer:sddfsf columnWidths:<nil> cssClass:ciw-text orientation...

12:22:30.663037 2018-04-10T12:22:30.663Z CRUD+: Did not update document "Observation::burakUWP" w/ xattr: 403 Invalid Observation document: item "templateRevisionInfo.schema" must not be null or missing; property "templateRevisionInfo.$schema" is not supported`

* Synctos: 2.2.1
* Couchbase Server: 5.0.1
* Sync Gateway: 1.5.1(4;cb9522c)

Thanks.

**Comment by OldSneerJaw** [comment]
@utekau: Thanks for the report. I will investigate. But, to help me do so, would you mind providing me the following:

* A copy of your document definitions or at least some contrived example document definitions that you're able to replicate the problem with
* Modify your Sync Gateway configuration to include the "HTTP+" [log](https://developer.couchbase.com/documentation/mobile/1.5/guides/sync-gateway/config-properties/index.html#1.5/log) key, then try to delete the document again and paste the resulting logs here
* Describe the client that is attempting the delete operation. For example, is it an iOS or Android Couchbase Lite app or is it an app that is using the Sync Gateway Public REST API directly?

**Comment by OldSneerJaw** [comment]
It appears from the logs you posted that there may be a conflict in the revision history that was not resolved correctly by a Couchbase Lite client. Specifically, it appears that the request in this case is promoting a previous losing revision (11-80a1e32f34ba86485260926d0d7d558c6c71acf7) as the new winner of an old CB Lite revision conflict and then attempting to run the current sync function on that old revision before proceeding. It fails, I suspect, because the document definitions that were in effect at the time of the conflict involving revision 11-80a1e32f34ba86485260926d0d7d558c6c71acf7 were not compatible with the current schema (e.g. the `templateRevisionInfo.schema` property used to be called `templateRevisionInfo.$schema`). In other words, the sync function isn't rejecting the revision from the DELETE operation, it is rejecting the old conflicted revision (11-80a1e32f34ba86485260926d0d7d558c6c71acf7).

My recommendation is to either rename that property back to its original name in your document definitions (in general, it's inadvisable to introduce breaking changes to your schema unless absolutely necessary anyway) and then try the DELETE operation again or to post the problem to the [Couchbase Mobile forum](https://forums.couchbase.com/c/mobile) for assistance from the Couchbase maintainers.

Either way, I do not believe this is a bug in synctos (or a bug in Sync Gateway, for that matter). I am closing this issue, at least for the time being. If new evidence comes to light to suggest that it is, in fact, a bug in synctos, we can reopen it then.

**Comment by utekau** [comment]
Thanks @OldSneerJaw for your investigation. As you mentioned, we didn't configure any conflict resolution mechanism and it resulted as we encountered above.
