### ISSUE TITLE
mustNotBeMissing validation not working as expected

### ISSUE THREAD

**Issue by utekau** [Kashoo/synctos#338]
# Bug Report

We are facing an issue when we use mustNotBeMissing field as a property validator.

## Steps to reproduce

1. We have a datetime object, we gave type like that. Lets call this field as y.
2. Validation was set as "mustNotBeMissing: true"
3. We added a document x by having this datetime property and value is null via cb server admin panel.

## Actual behaviour

We get the following error in sync gateway: Invalid x document: item "y" must not be missing;

## Expected behaviour

Actually field y is only null and is not missing or undefined. So it should be a valid document. When I debugged, I realized that "itemValue === void 0" is not returning expected result since itemValue interpretted as undefined, but it should has been null.

## Environment

* Synctos: 2.3.0
* Couchbase Server: 5.0.1
* Sync Gateway: 2.1
* Operating system: CentOs

Thanks.

**Comment by OldSneerJaw** [comment]
I have bad news, @utekau. It appears that, when a JSON document contains properties with `null` values, Sync Gateway removes those properties from the object that is passed to a sync function, which is why you're observing the behaviour you've described.

You can verify for yourself with the following sync function definition in a Sync Gateway config file:

```javascript
"sync": "function(doc, oldDoc) { throw { forbidden: 'JSON.stringify(doc): ' + JSON.stringify(doc) }; }"
```

Then upload a document like the following:

```javascript
{
  "type": "testDoc",
  "foo": {
    "bar": null,
    "baz": 183.9
  },
  "qux": null
}
```

You'll find that `foo.bar` and `qux` are altogether absent from the serialized output:

```javascript
{
    "error": "Forbidden",
    "reason": "JSON.stringify(doc): {\"_id\":\"test-doc\",\"_rev\":\"1-bb4abeae142ffddcfd504496d4f1f6a6\",\"foo\":{\"baz\":183.9},\"type\":\"testDoc\"}"
}
```

Since there does not appear to be a reliable way to retrieve the original JSON document to distinguish between `null` and missing values, I am going to deprecate the `mustNotBeMissing` and `mustNotBeNull` constraints. I suggest switching to the `required` constraint instead, even though it doesn't offer as fine-grained control as the other constraints were _supposed_ to offer.

**Comment by OldSneerJaw** [comment]
I have deprecated both `mustNotBeMissing` and `mustNotBeNull` in #339 since their behaviour is inconsistent with their intended purposes. Furthermore, the `mustNotBeNull` constraint has been modified so that it is triggered if the corresponding property is missing/`undefined` since that is how `null` property values end up represented in a sync function.
